### ISSUE TITLE
Model task sum to 1 check

### ISSUE THREAD

**Issue by breesie** [reichlab/variant-nowcast-hub#148]
Hi all!

While doing some model output comparisons for California we noticed certain tasks per date don't sum to 1. We were wondering why/ if the check is skipped when output_type=NA? 

ℹ [value_col_sum1]: No pmf output types to check for sum of 1. Check skipped. (this was for our submission)

Best,
Brent

**Comment by trobacker** [comment]
Hi @breesie, interesting point! 
Looking at the HubVerse source code a bit: this script [check_tbl_value_col_sum1.R](https://github.com/hubverse-org/hubValidations/blob/main/R/check_tbl_value_col_sum1.R) seems to be returning that message - assuming you used e.g. the `hubValidations::validate_model_data` to do a local validation check. Note that the check only runs for `pmf` value type. 

For this hub's validation procedures we do have another validation script [`clade_prop_sum_one.R`](https://github.com/reichlab/variant-nowcast-hub/blob/22970d3378f6860acb0ae6e16675f4fc614418fb/src/validations/R/clade_prop_sum_one.R#L4) to check for these clade proportions summing to 1. The first function checks across `output_type` of `sample` and checks that proportions sum to 1. I believe the function [`check_sum_one`](https://github.com/reichlab/variant-nowcast-hub/blob/22970d3378f6860acb0ae6e16675f4fc614418fb/src/validations/R/clade_prop_sum_one.R#L37) checks for sums otherwise. 

Did the validation pass on the PR with your tasks per date not summing to 1?

I'll keep investigating and if it did pass validation it may prompt some changes.

**Comment by nickreich** [comment]
Hi @breesie  - You said
> we noticed certain tasks per date don't sum to 1

Can you be more specific about which "tasks per date" you are referring to here, which submission, which location, date, etc...?

**Comment by tomasleon** [comment]
for posterity, addressed by #165
