### ISSUE TITLE
Update variant-nowcast-hub src/ scripts for cladetime API changes

### ISSUE THREAD

**Issue by bsweger** [reichlab/variant-nowcast-hub#153]
**Background**

Some of `cladetime`'s sequence-related function names have changed in recent weeks. The changes are backward-compatible, but let's make sure the variant-nowcast scripts are up-to-date.

**Defintion of done**

- [x] src/get_clades_to_model.py doesn't reference any deprecated cladetime function names
- [x] src/get_location_date_counts.py doesn't reference any deprecated cladetime function names

**Comment by lattaai10** [comment]
Hello, I tried to solve the issue.

This is what I did:

Updated the import statements and function calls to use the latest cladetime function names. Replaced deprecated 'filter_covid_genome_metadata' and 'get_clade_counts' with 'filter_genome_metadata' and 'get_counts' respectively.

You can review changes in this commit: https://github.com/lattaai10/reichlab-variant-nowcast-hub-153/commit/9964a4212a401c641b15d029fa0ce7537676b22e.


> [!CAUTION]
> Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---
This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
